#!/usr/bin/env bash

set -e

ALIAS="earthw"
REPO="github.com/earthly/earthly"
BIN="earth"
VERSION="" # leave empty to resolve the latest

LINK=${HOME}/.local/bin/${BIN}
mkdir -p $(dirname ${LINK})

LOCATION=${HOME}/.${ALIAS}
mkdir -p ${LOCATION}

if [[ -z "${VERSION}" ]] && LATEST_TAG=$(
  git -c 'versionsort.suffix=-' \
    ls-remote --tags --sort='v:refname' git://${REPO}.git \
    | tail --lines=1 \
    | cut --delimiter='/' --fields=3
); then
  VERSION=${LATEST_TAG}
fi

UPDATE_FILE=${LOCATION}/updated

if ! find ${UPDATE_FILE} -mtime -1 &> /dev/null \
&& [[ -n "${VERSION}" ]] \
&& VERSION_BIN=${LOCATION}/${VERSION}/${BIN} \
&& [[ ! -f ${VERSION_BIN} ]]; then
  echo "Updating..."

  OS=$(uname); OS=${OS,,}

  if ! [[ "${OS}" = "linux" || "${OS}" = "darwin" ]]; then
      echo "Unsupported operating system ${OS}"
      exit 1
  fi

  mkdir -p $(dirname ${VERSION_BIN})
  wget https://${REPO}/releases/download/${VERSION}/earth-${OS}-amd64 \
    -O ${VERSION_BIN}

  chmod +x ${VERSION_BIN}

  rm -f ${LINK}
  ln -s ${VERSION_BIN} ${LINK}

  touch ${UPDATE_FILE}
fi

# load aws credentials
eval $(
  python3 <<EOF
from configparser import ConfigParser
from os import getenv
from pathlib import Path

config = ConfigParser()
config.read(Path.home() / ".aws" / "credentials")
profileConfig = config[getenv("AWS_PROFILE", default="default")]

print("_AWS_ACCESS_KEY_ID=" + profileConfig["aws_access_key_id"])
print("_AWS_SECRET_ACCESS_KEY=" + profileConfig["aws_secret_access_key"])
EOF
)

# run earthly
${LINK} \
  --secret AWS_ACCESS_KEY_ID=${_AWS_ACCESS_KEY_ID} \
  --secret AWS_SECRET_ACCESS_KEY=${_AWS_SECRET_ACCESS_KEY} \
  ${@}

# cleaning up aws credentials
unset _AWS_ACCESS_KEY_ID
unset _AWS_SECRET_ACCESS_KEY
